### ISSUE TITLE
offer Issue 30 aug

### ISSUE THREAD

**Issue by Suman-Banakar** [Suman-Banakar/repo_30_aug#2]
testing

**Comment by angelleye-gitcommits** [comment]
GitCommits contributor has sent an offer to work on this issue.

**Offer Amount:** $55.00
**Message:** I can fix this for $50
<hr><a target='_blank' href='https://sandbox.app.gitcommits.com/offers/test1-sap-offer-issue-30-aug?action=accept'>Accept Offer</a> | <a target='_blank' href='https://sandbox.app.gitcommits.com/offers/test1-sap-offer-issue-30-aug?action=decline'>Decline Offer</a> | <a target='_blank' href='https://sandbox.app.gitcommits.com/offers/test1-sap-offer-issue-30-aug?action=counter'>Counter Offer</a>

**Comment by angelleye-gitcommits** [comment]
Congratulations <a target='_blank' href='https://sandbox.app.gitcommits.com/profile/Test1-sap'>Test1-sap</a>, Your offer has been accepted by the owner.

**Accepted offer Amount:** $55.00
**Owner Message:** Thank you, you can start work

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done**

<hr>

**The following Contributor have applied to start work .**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.app.gitcommits.com/profile/Test1-sap'>Test1-sap</a> has been approved to work.**

**Message:** I can fix this for $50



<hr>

**This issue has a bounty of $55.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/offer-issue-30-aug).
- Questions? Checkout [GitCommits Help](https://sandbox.app.gitcommits.com/help)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/Test1-sap'>Test1-sap</a> Work has been approved by <a href='https://sandbox.app.gitcommits.com/profile/Suman-Banakar'>Suman-Banakar</a>.**
<hr />

**Message:** Pull request has been approved, you will receive the payment shortly.


<a href='https://sandbox.app.gitcommits.com/issue/offer-issue-30-aug'>Click Here to view more</a> on GitCommits Bounty detail page.
