### ISSUE TITLE
Contest Issue 30 aug

### ISSUE THREAD

**Issue by Suman-Banakar** [Suman-Banakar/repo_30_aug#8]
contest issue 30 aug

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done**

<hr>

**The following Contributors have begun work and are competing for the bounty. .**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.app.gitcommits.com/profile/Test1-sap'>Test1-sap</a> started work on the bounty on 30 Aug.**

**Message:** started work on this


**2) <a href='https://sandbox.app.gitcommits.com/profile/PujaGovind'>PujaGovind</a> has been approved to work.**

**Message:** I have also started work on this



<hr>

**This issue has a bounty of $66.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/contest-issue-30-aug).
- Questions? Checkout [GitCommits Help](https://sandbox.app.gitcommits.com/help)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/Test1-sap'>Test1-sap</a>, has started work on the bounty.**
<hr />

**Message:** started work on this


<a href='https://sandbox.app.gitcommits.com/issue/contest-issue-30-aug'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/PujaGovind'>PujaGovind</a>, has started work on the bounty.**
<hr />

**Message:** I have also started work on this


<a href='https://sandbox.app.gitcommits.com/issue/contest-issue-30-aug'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/PujaGovind'>PujaGovind</a> Work has been approved by <a href='https://sandbox.app.gitcommits.com/profile/Suman-Banakar'>Suman-Banakar</a>.**
<hr />

**Message:** Pull request has been approved, you will receive the payment shortly.


<a href='https://sandbox.app.gitcommits.com/issue/contest-issue-30-aug'>Click Here to view more</a> on GitCommits Bounty detail page.
